"""invites table + membership self-visibility RLS policy

Revision ID: 0004_invites
Revises: 0003_refresh_tokens
Create Date: 2026-09-16

`invites` is autogenerated against pulse.models, not RLS-protected despite
carrying org_id -- see SPEC.md #4.1 and pulse/models/invite.py's docstring
for why (it's a token-redemption table, the same reasoning as refresh_tokens).

The second half is hand-written: a second, FOR SELECT-only permissive
policy on memberships, so a user can list "which orgs am I in" (visible by
user_id) without loosening the org-scoped WITH CHECK that governs writes.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004_invites"
down_revision: str | None = "0003_refresh_tokens"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "invites",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "OWNER", "ADMIN", "MEMBER", "VIEWER", name="membership_role", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("invited_by", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_invites_token_hash"), "invites", ["token_hash"], unique=True)

    op.execute(
        """
        CREATE POLICY member_self_visibility ON memberships
            FOR SELECT
            USING (user_id = current_setting('app.current_user_id', true)::uuid)
        """
    )


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS member_self_visibility ON memberships")

    op.drop_index(op.f("ix_invites_token_hash"), table_name="invites")
    op.drop_table("invites")
