"""api keys

Revision ID: 0006_api_keys
Revises: 0005_audit_logs
Create Date: 2026-09-17

Autogenerated against pulse.models, then hand-edited: not RLS-protected,
despite carrying org_id/project_id -- like refresh_tokens/invites, this is
a token-redemption table (validated by an opaque secret before any org
context is known). Management endpoints filter by org_id/project_id
explicitly instead. See SPEC.md #4.1 and pulse/models/api_key.py.

Also added an explicit DROP TYPE to downgrade(): op.drop_table() issues a
bare DROP TABLE without reconstructing column type metadata, so it does
NOT drop an associated Postgres enum -- the same gap 0002's downgrade
already had to work around for membership_role.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0006_api_keys"
down_revision: str | None = "0005_audit_logs"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "api_keys",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("type", postgresql.ENUM("WRITE", "READ", name="api_key_type"), nullable=False),
        sa.Column("key_prefix", sa.String(), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)


def downgrade() -> None:
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.execute("DROP TYPE api_key_type")
