"""schema registry

Revision ID: 0007_schema_registry
Revises: 0006_api_keys
Create Date: 2026-09-17

Autogenerated against pulse.models, then hand-edited: RLS-protected on
org_id, like audit_logs/projects -- a browse-this-project's-taxonomy
pattern, not token redemption. See SPEC.md #4.1 and #6.6.

schema_status is shared by both event_schemas.status and
property_schemas.status -- created explicitly once (checkfirst=True) before
either table, then referenced with create_type=False on both columns, since
op.create_table() would otherwise try to CREATE TYPE it a second time.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0007_schema_registry"
down_revision: str | None = "0006_api_keys"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_schema_status = postgresql.ENUM(
    "ACTIVE", "DEPRECATED", "HIDDEN", name="schema_status", create_type=False
)
_property_type = postgresql.ENUM(
    "STRING", "NUMBER", "BOOL", "DATETIME", name="property_type", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    _schema_status.create(bind, checkfirst=True)
    _property_type.create(bind, checkfirst=True)

    op.create_table(
        "event_schemas",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("event_name", sa.String(), nullable=False),
        sa.Column("status", _schema_status, nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("volume_estimate", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "event_name", name="uq_event_schemas_project_event"),
    )
    op.execute("ALTER TABLE event_schemas ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE event_schemas FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON event_schemas
            USING (org_id = current_setting('app.current_org_id', true)::uuid)
            WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid)
        """
    )

    op.create_table(
        "property_schemas",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("event_schema_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("inferred_type", _property_type, nullable=False),
        sa.Column("is_pii", sa.Boolean(), nullable=False),
        sa.Column("status", _schema_status, nullable=False),
        sa.Column("type_conflict_detected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["org_id"], ["organizations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_schema_id"], ["event_schemas.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_schema_id", "key", name="uq_property_schemas_event_key"),
    )
    op.execute("ALTER TABLE property_schemas ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE property_schemas FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON property_schemas
            USING (org_id = current_setting('app.current_org_id', true)::uuid)
            WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid)
        """
    )


def downgrade() -> None:
    op.drop_table("property_schemas")
    op.drop_table("event_schemas")
    op.execute("DROP TYPE property_type")
    op.execute("DROP TYPE schema_status")
